# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('active', models.BooleanField(verbose_name='active')),
                ('available_on', models.DateTimeField(blank=True, null=True, verbose_name='available on')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='SKU')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='wtcproducts.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
