# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtailcommerce.shipping.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcommerce_stores', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=255, verbose_name='tracking code')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
            ],
            options={
                'verbose_name': 'shipment',
                'verbose_name_plural': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=models.SET(wagtailcommerce.shipping.models.get_default_shipping_method_content_type), related_name='shipping_methods', to='contenttypes.ContentType', verbose_name='content type')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_methods', to='wagtailcommerce_stores.Store')),
            ],
            options={
                'verbose_name': 'shipping method',
                'verbose_name_plural': 'shipping methods',
            },
            bases=(wagtailcommerce.shipping.models.ShippingMethodBase, wagtailcommerce.shipping.models.AbstractShippingMethod, models.Model),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='wagtailcommerce_shipping.ShippingMethod'),
        ),
    ]
