# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_carts', '0003_auto_20171120_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wagtailcommerce_carts.Cart'),
            preserve_default=False,
        ),
    ]
