# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_carts', '0004_cartline_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='token',
        ),
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
