# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_carts', '0005_auto_20171203_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='token'),
        ),
    ]
