# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import wagtailcommerce.wtcshipping.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'shipping method',
                'verbose_name_plural': 'shipping methods',
            },
            bases=(wagtailcommerce.wtcshipping.models.ShippingMethodBase, wagtailcommerce.wtcshipping.models.AbstractShippingMethod, models.Model),
        ),
    ]
