# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wtcshipping', '0001_initial'),
        ('wtcstores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_methods', to='wtcstores.Store'),
        ),
    ]
