# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='last_name')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='company')),
                ('street_address_1', models.CharField(blank=True, max_length=255, verbose_name='address (line 1)')),
                ('street_address_2', models.CharField(blank=True, max_length=255, verbose_name='address (line 2)')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='city / town')),
                ('city_area', models.CharField(blank=True, max_length=255, verbose_name='district / neighborhood')),
                ('country_area', models.CharField(blank=True, max_length=255, verbose_name='state / province')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='country')),
                ('postal_code', models.CharField(blank=True, max_length=64, verbose_name='postal code')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
